version: '3'

volumes:
  postgres_volume:

services:
  pg:
    image: postgres:14-alpine3.17
    environment:
      - "POSTGRES_DB=${PG_DATABASE_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    networks:
      - diplom-net
  migrator:
    build:
      context: .
      dockerfile: migration.Dockerfile
    restart: on-failure
    networks:
      - diplom-net
  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - diplom-net
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
  # app:  
  #   image: diploma-server:${TAG_NAME}
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - "./.env:/root/.env"
  #   depends_on:
  #     - pg
  #   networks:
  #     - diplom-net
  #   env_file:
  #     - .env

networks:
  diplom-net:
    driver: bridge

