global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'diploma-app'
    static_configs:
      - targets:
        - 'app:8080'
    metrics_path: '/metrics'

  - job_name: 'prometheus'
    static_configs:
      - targets:
        - 'prometheus:9090' 